enum MessageTypes
{
    BROADCAST = 1,
    UNICAST = 2,
    SCHEDULE_SYNC = 3,
    SLAVE = 4,
    MASTER = 5,
    SYNC = 6,
    FOLLOW_UP = 7,
    DELAY_REQ = 8,
    DELAY_RESP = 9,
    SCHEDULE_FOLLOW_UP= 10,
    SCHEDULE_DELAY_REQ = 11,
    SCHEDULE_DELAY =12,
    POSITION_UPDATE =13
};
